export interface AulaHorarioSemana {
    id_aula: number;
    id_horario: number;
    id_semana: number;
    fecha_programada?: string; // Optional because it's generated by trigger, but useful to have if returned
}
